---
- name: modify spark-defaults.conf
  hosts: spark
  tasks:
    - name: modify spark-defaults.conf
      blockinfile:
        path: /engine/spark-3.5.1-bin-hadoop3/conf/spark-defaults.conf
        block: |
          spark.master yarn
          spark.deploy.mode client
          spark.serializer org.apache.spark.serializer.KryoSerializer
          spark.sql.shuffle.partitions 6
        marker: "# {mark} Setting spark-defaults.conf"
        create: true
        owner: spark
        group: spark
      become: yes