---
- name: install Zookeeper
  hosts: kafka
  tasks:
    - name: Add Zookeeper group
      ansible.builtin.group:
        name: zookeeper
        gid: 1002
        system: false
      become: yes

    - name: Add Zookeeper user
      ansible.builtin.user:
        name: zookeeper
        shell: /bin/bash
        uid: 1002
        group: zookeeper
        comment: User for Zookeeper
      become: yes

    - name: make directory
      ansible.builtin.file:
        path: /engine
        state: directory
      become: yes

    - name: unarchive file
      ansible.builtin.unarchive:
        src: /home/ec2-user/downloads/apache-zookeeper-3.8.4-bin.tar.gz
        dest: /engine
        copy: true
        owner: zookeeper
        group: zookeeper
      become: yes

    - name: Install Java 17
      ansible.builtin.apt:
        name: openjdk-17-jre
        update_cache: true
      become: yes
