---
- name: Setting /etc/hosts file
  hosts: spark
  tasks:
    - name: setting spark hosts
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.26.63 kafka01
          172.31.35.214 kafka02
          172.31.50.199 kafka03
          172.31.22.184 spark01 
          172.31.39.142 spark02
          172.31.56.14 spark03
        marker: "# {mark} Setting datalake hosts"
      become: yes

    - name: setting hostname
      lineinfile:
        path: /etc/hostname
        regexp: '^(ip|spark)'
        line: '{{ inventory_hostname }}'
      become: yes

    - name: change timezone
      command:
        cmd: timedatectl set-timezone Asia/Seoul
      become: yes