---
- name: Setting Zookeeper Service
  hosts: kafka
  tasks:
    - name: Copy zoo_sample.cfg to zoo.cfg
      copy:
        src: /engine/apache-zookeeper-3.8.4-bin/conf/zoo_sample.cfg
        dest: /engine/apache-zookeeper-3.8.4-bin/conf/zoo.cfg
        remote_src: yes
        owner: zookeeper
        group: zookeeper
      become: yes
    - name: Create zookeeper data directory
      file:
        path: /data/zookeeper
        owner: zookeeper
        group: zookeeper
        state: directory
      become: yes
    - name: create myid file
      lineinfile:
        path: /data/zookeeper/myid
        create: yes
        state: present
        owner: zookeeper
        group: zookeeper
        regex: '^[0-9]'
        line: '{{ kafka_broker_no }}'
      become: yes
    - name: setting zoo.cfg
      lineinfile:
        path: /engine/apache-zookeeper-3.8.4-bin/conf/zoo.cfg
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: '^dataDir', line: 'dataDir=/data/zookeeper' }
        - { regexp: '^server1', line: 'server.1=kafka01:2888:3888' }
        - { regexp: '^server2', line: 'server.2=kafka02:2888:3888' }
        - { regexp: '^server3', line: 'server.3=kafka03:2888:3888' }
      become: yes
